export interface EMR_TREATMENT {
    BRANCH_CODE: string;
    CARD_CODE: string;
    CLINICAL_IN_TIME: number | null;
    CURRENT_DEPARTMENT_CODE: string;
    CURRENT_DEPARTMENT_NAME: string;
    DATA_STORE_CODE: string;
    DATA_STORE_NAME: string;
    DOB: number;
    AVATAR_URL: string;
    END_CODE: string;
    GENDER_CODE: string;
    GENDER_NAME: string;
    HEIN_CARD_NUMBER: string;
    HEIN_TREATMENT_TYPE_CODE: string;
    ICD_CODE: string;
    ICD_NAME: string;
    ICD_SUB_CODE: string;
    ICD_TEXT: string;
    FIRST_NAME: string;
    ID: number;
    IN_CODE: string;
    IN_DATE: number;
    IS_EMERGENCY: number | null;
    IS_HAS_NOT_DAY_DOB: number | null;
    LAST_NAME: string;
    OUT_CODE: string;
    OUT_DATE: number | null;
    OUT_TIME: number | null;
    PATIENT_CODE: string;
    PATIENT_TYPE_CODE: string;
    IN_TIME: number;
    PATIENT_TYPE_NAME: string;
    STORE_DATE: number | null;
    STORE_TIME: number | null;
    TREATMENT_CODE: string;
    TREATMENT_END_TYPE_CODE: string;
    TREATMENT_END_TYPE_NAME: string;
    TREATMENT_RESULT_CODE: string;
    TREATMENT_RESULT_NAME: string;
    TREATMENT_TYPE_CODE: string;
    STORE_CODE: string;
    TREATMENT_TYPE_NAME: string;
    VIR_PATIENT_NAME: string;
}